### ISSUE TITLE
Issue 1 Create EventCatalog Class

### ISSUE THREAD

**Issue by kaurgurpal** [kaurgurpal/Eventbrite#1]
Start by defining properties for the EventCatalog

**Comment by kaurgurpal** [comment]
1. int EventId
2. string EventTitle
3. int EventLocationId  (what if online event? 0?)
4. bool ShowMap
5. datetime EventStartDate
6. datetime EventStartTime
7. datetime EventEndDate
8. datetime EventEndTime
9. string EventImageUrl
10. string EventDescription
11. string EventOrganizerName
12. string EventOrganizerdescription
13. string EventFacebooklink
14. string EventTwitterLink

15. int EventTypeId (Named as Type on eventbrite website)
16. int EventCategoryId (Named as Topic on eventbrite website)

**Comment by kaurgurpal** [comment]
![image](https://user-images.githubusercontent.com/9306171/64814938-5a948800-d559-11e9-8e7c-16fea5efe1c8.png)

![image](https://user-images.githubusercontent.com/9306171/64815006-8283eb80-d559-11e9-827b-a2a2c417f15d.png)

**Comment by sstambat12** [comment]
To these Properties, we can add 
decimal EventTicketPrice 
property .

**Comment by kaurgurpal** [comment]
I was wondering if Ticket is going to be a separate microservice??
As every event can have multiple types of tickets, different number of available tickets etc.

**Comment by sstambat12** [comment]
yes, that will be a separate microservice where ticket will be seen by user only if he/she wants to register for that event. As in this microservice we are going to show Events catalog, we need to show starting ticket price also(As Events on eventbrite website also displays)
